[global]
inputdirectory = "testdir"
hierarchical=true
traversal="topdown"
parallel=true
regex=true
common_actions = {do_on_invalid=[["all", "show_warning", ["log_to_file", "errors.txt"]]]}
common_conditions = {is_3d_channel=["endswith", "[0,1].tif"], dir_only=[["all", "isdir", ["not", "is_hidden"]]]}
file_lists=[{name="in", aggregator=[["filepath","sort","unique","shared_list_to_file"]]},
              {name="out", aggregator=[[["change_path", "outpath"],"filepath","sort","unique","shared_list_to_file"]]}]
[any]
conditions=["never"]
actions=["do_on_invalid"]

[level_1]
conditions=["dir_only"]
actions=["do_on_invalid"]

[level_2]
all=true
conditions=["dir_only", "ends_with_integer", ["startswith", "Replicate"]]
actions=["do_on_invalid"]

[level_3]
conditions=["dir_only"]
actions=["do_on_invalid"]

[level_4]
all=true
conditions=["dir_only", ["startswith", "Serie"], "ends_with_integer"]
actions=["do_on_invalid"]

[level_5]
conditions=["is_3d_channel"]
actions=["do_on_invalid"]
counter_actions=[["->", ["in","out"]]]
